name: easy_cli
description: >-
  CLI utility that generates a folder structure to reduce the repetitive work required to setup directories for models, services, repositories, screens and widgets.
version: 0.2.3

homepage: https://github.com/RyanDsilva/feature_folder_cli

documentation: https://github.com/RyanDsilva/feature_folder_cli#folder-by-feature-cli-utility

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  ansicolor: ^2.0.1
  args: ^2.1.1
  path: ^1.8.0
  recase: ^4.0.0

dev_dependencies:
  test: ^1.17.10

executables:
  easy: main